language: python
python:
  - '2.7'
sudo: required
dist: trusty
install:
  - source cfg4dev
  - pip install coveralls
  - sudo apt-get install -y docker.io
script:
  - pep8
  - flake8
  - nosetests --verbosity=4 --with-coverage --cover-branches --cover-erase --cover-package cloudfeaster
  - coveralls || true
  - python setup.py sdist --formats=gztar
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-image.sh -v -t "$TRAVIS_TAG" ./dist/cloudfeaster-*.*.*.tar.gz $DOCKER_USERNAME $DOCKER_EMAIL $DOCKER_PASSWORD; fi
