language: python
python:
- '2.7'
install:
- export CHROME_BIN=chromium-browser
- source cfg4dev
- pip install coveralls
script:
- pep8
- flake8
- nosetests --with-coverage --cover-branches --cover-erase --cover-package cloudfeaster
- coveralls
