language: python
python:
  - '2.7'
sudo: required
services:
  - docker
install:
  - source cfg4dev
  - pip install coveralls
script:
  - pep8
  - flake8
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package cloudfeaster
  - coveralls
after_success:
  - python setup.py sdist --formats=gztar
  - ./dockerfiles/build-docker-images.sh $DOCKER_EMAIL $DOCKER_USERNAME $DOCKER_PASSWORD ./dist/cloudfeaster-*.*.*.tar.gz
