language: python
python:
  - '2.7'
sudo: required
dist: trusty
install:
  - source cfg4dev
  - pip install coveralls
  - sudo apt-get install -y docker.io
script:
  - pep8
  - flake8
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package cloudfeaster
  - python setup.py sdist --formats=gztar
  - coveralls
  - ./dockerfiles/build-docker-images.sh ./dist/cloudfeaster-*.*.*.tar.gz $DOCKER_USERNAME $DOCKER_EMAIL $DOCKER_PASSWORD
