language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  - DOCKER_TEMP_IMAGE=simonsdave/cloudfeaster:bindle
install:
  - source cfg4dev
  - pip install coveralls
  - docker pull koalaman/shellcheck:latest
script:
  - run_pip_check.sh
  - run_flake8.sh
  - run_shellcheck.sh -v
  - run_repo_security_scanner.sh
  - travis_fold start "build.python.packages"
  - build_python_package.sh
  - travis_fold end "build.python.packages"
  # run_unit_tests.sh bin/tests cloudfeaster
  # fails on bin/tests - for now running just
  # the basic unit tests so travis works
  - run_unit_tests.sh
  - travis_fold start "build.docker.image"
  - ./dockerfiles/build-docker-image.sh ./dist/cloudfeaster-*.*.*.tar.gz ${DOCKER_TEMP_IMAGE}
  - travis_fold end "build.docker.image"
  - tests/integration/docker_image_integration_tests.sh "$DOCKER_TEMP_IMAGE" "$PYPI_USERNAME" "$PYPI_PASSWORD"
after_success:
  - coveralls || true
deploy:
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh ${DOCKER_TEMP_IMAGE} ${DOCKER_USERNAME} ${DOCKER_PASSWORD} latest
    on:
      branch: master
  - provider: script
    script: ./dockerfiles/tag-and-push-docker-image.sh ${DOCKER_TEMP_IMAGE} ${DOCKER_USERNAME} ${DOCKER_PASSWORD} v${TRAVIS_BRANCH##release-}
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^release-([0-9]+.)*[0-9]+$"
notifications:
  - slack:
    on_success: always
    on_failure: always
    rooms:
      secure: gUC7OIsiH1kgXOJthLuJWZSbIykEZme8jRdq0ZLZrM2dePKRmiiT8+dRDhPr5RRxK3/bhx0tQ6eJX2PvLwSL8L7rpcPUFlHHbwtW1gwaJKpZuOrwbXPc+35lpIBiJ6AZCmqJmOu3kW0t8AJ1EKOx2zJeRQOMIOWRRCe0LOGsKyFZlohEXsKSS7P/JnY7KV435W+J2lGzua/9X4qUVQfLmiCt+pgBw5xdBhx+7D1wGLhlEAJebgS0s6PJJo2zLQ9AxyMnCArU2d8djvcVmK2WbTkrxA30sxN/7osCOEt25T+hqov8CVkeXUnzM9NfFPByamJFwQ14n8dnaUz+hCwFM4lK1AvaabbmiRmIcn1oikOz+PaDvXWv2+6wjiff8LFRpMrIVEIAqeczWwhX+F7TU8ZjV3x7IA4wIkIfImjtI8WN7kXDiI/uaT1DiaLDAP40584c9t2bme7VndeBq0D20KwxfQvmjJ7lsWUUCdSmbuBonodvI8LLgRQLTLRZGx0fftaUseRqSjBWkdbzpgpVhFtDNykdZA7KvUr5qmONhj/hIgk8GTTcDHFjI1/PovnSHFL90bjzllftrM0cqaNUnGX2Hy/mmBlzNKncpApxmc5tT9U2ti6qp0VZUtaU+uQGLhZB0VXLYPNcFD4ue0SbKZ6TPRP8/5Vs8X0teJza7mg=
