#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=X
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/31d176dcb26e35eb23d040a31bcf041a
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.socket
      command: start
      drop-ins:
      - name: 30-ListenStream.conf
        content: |
          [Socket]
          ListenStream=127.0.0.1:49153
    - name: fleet.service
      command: start
